---
version: 4.0.0

collections_dir: collections
collections:
  comics:
    output: true
    sort_by: number
  test:
    output: true
    sort_by: number
  another:
    output: true
    sort_by: number

defaults:
  - scope:
      path: "assets/comics"
    values:
      comic: true

sass:
  sass_dir: _sass
  style: compressed

# Chapters and Sections with collections
# https://stackoverflow.com/a/37770419

# Photo gallery with Jackyll
# http://chrisbreitigan.com/blog/photo-galleries-with-data-files
# http://garethlewis.io/blog/2016/05/21/building-my-photo-gallery-the-jekyll-way/

# Loop static_files to make a gallery
# https://mademistakes.com/notes/static-files/

exclude:
- ".gitignore"
- ".jekyll-cache"
- CNAME
- README.md
